In [2]:
import numpy as np

In [3]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [4]:
type(a[0]) # float element

numpy.float64

In [5]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
z.shape

(10,)

In [7]:
z.shape = (10,1) # change shape
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [8]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
z = np.empty(3) #  doesn't have its values initialized, create empty for us to fill
z

array([0., 0., 0.])

In [10]:
z = np.linspace(2,10,5) # from 2 to 10 with 5 elements
z # plot

array([ 2.,  4.,  6.,  8., 10.])

In [11]:
z = np.array([10,20]) # create an array
z 

array([10, 20])

In [12]:
b_list = [[9,8,7,6,5,4,3], [1,2,3,4,5,6,7]]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [13]:
z.shape
#?z # get information about z

(1, 2, 7)

In [14]:
np.random.seed(0) # make sure each random the same
z1 = np.random.randint(10, size=6) # [0,low)
z1


array([5, 0, 3, 3, 7, 9])

In [15]:
z1[0]

5

In [16]:
z1[0:2]

array([5, 0])

In [17]:
z1[-1]

9

In [18]:
z = np.array([1,2,3,4,5])

In [19]:
z < 3

array([ True,  True, False, False, False])

In [20]:
z > 3

array([False, False, False,  True,  True])

In [21]:
z[z>3]

array([4, 5])

In [22]:
photo_masked = np.where(photo > 100, 255, 0)

NameError: ignored

In [25]:
a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])

# +, * 对应位置的元素进行

In [26]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [27]:
a_array + 30

array([31, 32, 33, 34, 35])

In [28]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [29]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [30]:
a_array * 10

array([10, 20, 30, 40, 50])

In [31]:
a_array @ b_array # dot product

130

In [32]:
photo[:,:,0].T # transpose

NameError: ignored

In [34]:
x = np.array([2,1,4,3,5])
np.sort(x)  # sort an array

array([1, 2, 3, 4, 5])

In [35]:
a_array

array([1, 2, 3, 4, 5])

In [36]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
type(a)

numpy.ndarray

In [37]:
a[:,0] #all rows, 0 column

array([1, 4, 7])

In [38]:
a[2,1] # row 2, column1

8

In [39]:
a[:2, 1] # row 0 to 1, column 1

array([2, 5])

In [40]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [41]:
a.reshape(-1,1) 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [42]:
a_array

array([1, 2, 3, 4, 5])

In [43]:
a_array.ndim

1

In [44]:
type(a_array[0])

numpy.int64

In [45]:
a_array.dtype

dtype('int64')

In [46]:
a_array.itemsize

8

In [47]:
a_array.size # total number of elements

5

# Accessing/Changing specific elements, rows, etc

In [48]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [49]:
# get a specific element[r,c]
a[1,5]

13

In [50]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
# get a specific column
a[:,2]

array([ 3, 10])

In [52]:
# get a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]
#a[0,1:-1:2] # same

array([2, 4, 6])

In [53]:
 a[1,5] = 20
 print(a)

 a[:,2] = 5
 print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


## 3-d example

In [54]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
# get specific element(work outside in)
b[0, 1,:] # the first element, row 1 column 1

array([3, 4])

In [56]:
# replace
b[:,1,:] = [9,9], [8, 8]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of arrays

In [57]:
# all 0s matrix
np.zeros((2,3)) # tuple inside

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
#all 1s matrix
np.zeros((2,3), dtype="int32")

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [59]:
# any other number
np.full((2,2), 99, dtype ="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [60]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [61]:
# Any other number(full_like)
np.full_like(a, 4) # a= a shape

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [62]:
# random decimal numbers
np.random.rand(4,2)

array([[0.6235637 , 0.38438171],
       [0.29753461, 0.05671298],
       [0.27265629, 0.47766512],
       [0.81216873, 0.47997717]])

In [63]:
# random integer values
np.random.randint(-4,8, size = (3,3)) # from [-4,8)

array([[-3,  1,  5],
       [ 4,  5,  0],
       [-1, -4, -1]])

In [64]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
arr = np.array([[1,2,3]]) # 2-dim
r1 = np.repeat(arr, 3, axis = 0) # axis = 0 is row
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [66]:
# output = np.ones((5,5), dtype = int)
# output[1:4,1:4] = 0
# output[2,2] = 9
# print(output)

In [67]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!

In [68]:
 a = np.array([1,2,3])
 b = a # 
 b[0] =100
 print(a)
 print(b)

[100   2   3]
[100   2   3]


In [69]:
b = a.copy()
b[0] = 200
print(a)
print(b)

[100   2   3]
[200   2   3]


# Mathematics

In [70]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [71]:
a + 2

array([3, 4, 5, 6])

In [72]:
a*2

array([2, 4, 6, 8])

In [73]:
a**2

array([ 1,  4,  9, 16])

In [74]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### linear algebra

In [105]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
#a*b  # error
print(b)

np.matmul(a,b)
"""
same as below:
b.T
a@b
"""

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


'\nsame as below:\nb.T\na@b\n'

In [76]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##Statistics

In [77]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.min(stats)

1

In [79]:
np.min(stats, axis=0)

array([1, 2, 3])

In [80]:
np.min(stats, axis=1)

array([1, 4])

In [81]:
np.sum(stats)  # axis

21

In [82]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [83]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous
#### Load data from file

In [87]:
"""
filedata = np.genfromtxt("data.txt", delimiter=",")
filedata = filedata.astype("int32")
filedata
"""

'\nfiledata = np.genfromtxt("data.txt", delimiter=",")\nfiledata = filedata.astype("int32")\nfiledata\n'

## Boolean Masking and Advanced Indexing

In [89]:
#filedata [filedata < 50]

In [90]:
# index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])